# Generated by Django 5.1.4 on 2024-12-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0002_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cod_fornecedor',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
