# Generated by Django 5.1.4 on 2024-12-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0005_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(to='DSW_ATV.categoria'),
        ),
    ]
