# Generated by Django 5.1.4 on 2024-12-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0006_produto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='fornecer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DSW_ATV.produto'),
            preserve_default=False,
        ),
    ]
